name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t pgscen .

      - name: Run tests
        run: docker run --rm pgscen micromamba run -n base bash -c "bash test/test_run.sh"

