name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          auto-activate-base: false

      - name: test-run
        shell: bash -l {0}
        run: |
          pip install .
          sh test/test_run.sh
          echo tests finished successfully!

